<?php

/***************************************
 * phpAce Bulk Image Converter V1.0
 * Copyright 2008 Sam Yapp
 * http://www.phpace.com/products/bulk-image-converter/
 *
 * Support Forum: http://forum.phpace.com/
 *
 * You may not sell or distribute this 
 * script without the express written 
 * permission of the author.
 ***************************************/

/************** DO NOT EDIT THIS FILE ****************
 * Instead of editing this file with your own translations,
 * create a copy of it with a new name and edit that instead,
 * then set the value of the configuration option $pabi_config['language'] to 
 * the name of your file (without the .php extension).
 * The configuration setting is in the config.php file.
 *
 * Doing so will prevent your translations and modifications being overwritten 
 * when you upgrade the script.
 *
 */

// initialize the translations array
$pabi_lang = array();

/*
 For each translation you want to modify, edit only the text after the = or <<<EOL
 This file is a php file, and the translations are stored as php strings.
 You must ensure that the translation strings you define are correctly formatted for php
 Strings must be enclosed in:
 - single quotes, eg. 'this is a string';
 - double quotes, eg. "this is a string";
 - php heredoc syntax, eg. <<<EOL
this is a string
that uses heredoc syntax :)
EOL;

 For non php coders, be aware of the following "gotchas"

 - Remember to add a semicolon ; at the end of the line.

 - If you need to add quote marks (") inside a string, you should either
	 enclose the string in single quotes, eg:

			$pabi_lang['some message'] = 'this string has "quote marks" in it';

	 or escape the quote marks using a backslash \, if using double quotes: eg.

			$pabi_lang['some message'] = "this string has \"quote marks\" in it";

	- In strings with double quotes and strings using heredoc syntax (<<<EOL ... EOL; )
		you need to escape any use of the dollar $ sign, as otherwise php looks for a
		variable with that name to include in the string, eg:

			$pabi_lang['some message'] = "php will think $this is a variable";
			$pabi_lang['some message'] = "php will not think \$this is a variable";


	Unless otherwise noted, the script uses the htmlspecialchars function
	on all translations, so you do not need to worry about writing html entities,
	like &gt; &quot; for > and " etc.

*/

/****************** Meta description / keywords ***********************/

// meta keywords
$pabi_lang['Meta Keywords'] = <<<EOL
bulk image resizer, image converter, resize photos, watermark photos
EOL;

// meta description
$pabi_lang['Meta Description'] = <<<EOL
Upload single images or multiple images in a zip archive, resize them all at once,
add watermarks and convert to jpeg, gif or png.
EOL;

// intro text at the top of the page
// Use HTML here, it won't be escaped with htmlspecialchars
$pabi_lang['Intro Text'] = <<<EOL
Upload single images or multiple images in a zip archive, resize them all at once,
add watermarks and convert to jpeg, gif or png.
EOL;

/****************** Messages in layout.php ****************************/

// heading above the upload field
$pabi_lang['Upload an image or zip'] = 'Upload an image or zip archive';

// temporary variable used in upload instructions
$pabi_max_post_size = ini_get('post_max_size');
// instructions for uploading images.
// This should be HTML code as it is not escaped with htmlspecialchars
$pabi_lang['Upload Instructions'] = <<<EOL
Select a jpeg, png or gif image to convert, or upload a zip archive of images for batch conversion.
Max individual image filesize: {$pabi_config['max_image_filesize']}Mb. 
Max {$pabi_config['max_images']} images at a time.
Max zip filesize: {$pabi_max_post_size}
EOL;

// heading displayed at top after images converted
$pabi_lang['Images Converted'] = 'Images Converted';

// label on the "Download" button
$pabi_lang['Download'] = 'Download';

// label on the "Convert More" button
$pabi_lang['Convert More'] = 'Convert More';

// instructions for downloading a single image.
// This should be HTML code as it is not escaped with htmlspecialchars
$pabi_lang['Download Image Instructions'] = <<<EOL
Click the download button to download your converted image.
EOL;

// instructions for downloading zip of images
// This should be HTML code as it is not escaped with htmlspecialchars
$pabi_lang['Download Zip Instructions'] = <<<EOL
Click the download button to download your converted images as a zip archive.
EOL;

// instructions for converting the images again
// This should be HTML code as it is not escaped with htmlspecialchars
$pabi_lang['Convert Again Instructions'] = <<<EOL
Click the Convert More button to upload more images to convert.
<br /><br />
You can change your options and reconvert your images below.
EOL;

// Error Messages Heading
$pabi_lang['Error Messags'] = 'Error Messages';

// Heading for resize options
$pabi_lang['Resize Options'] = 'Resize Options';

// label next to checkbox to resize images
$pabi_lang['Resize Images?'] = 'Resize Images?';

// label above common sizes drop-down select box
$pabi_lang['Common Sizes'] = 'Common Sizes';

// labels for common size options
$pabi_lang['50x50'] = 'Small Thumbnails';
$pabi_lang['120x120'] = 'Thumbnails';
$pabi_lang['200x200'] = 'Large Thumbnails';
$pabi_lang['320x200'] = 'Small Images';
$pabi_lang['640x480'] = 'Good For Email';
$pabi_lang['800x600'] = 'Medium Images';
$pabi_lang['1024x768'] = 'Large Images';
$pabi_lang['1200x1024'] = 'Largest Images';

// Custom Size Label
$pabi_lang['Custom Size'] = 'Custom Size';

// instructions for resizing images.
// This should be HTML code as it is not escaped with htmlspecialchars
$pabi_lang['Resize Instructions'] = <<<EOL
Check the box if you want to resize your image(s).
<br /><br />
Select a default size or enter a custom width and height.
Images will be resized proportionally.
<br /><br />
If you specify just one of the width or height then images
will be resized to fit this dimension.
EOL;

// Heading for watermark options
$pabi_lang['Watermark Options'] = 'Watermark Options';

// Label above Watermark Text
$pabi_lang['Watermark Text'] = 'Watermark Text';

// Label above transparency
$pabi_lang['Transparency'] = 'Transparency';

// Label above watermark location
$pabi_lang['Watermark Location'] = 'Watermark Location';

// Label above watermark size
$pabi_lang['Watermark Size'] = 'Watermark Size';

// instructions for watermarking images.
// This should be HTML code as it is not escaped with htmlspecialchars
$pabi_lang['Watermark Instructions'] = <<<EOL
Add a watermark to your images by entering the text you want to display.
<br /><br />
You can set the text to be partially transparent by entering a value from
0% to 100%.
<br /><br />
Select the location on the image where you want the watermark to appear.
<br /><br />
Enter the font size of the watermark text (8 is very small, 50 very large).
EOL;

// Heading for conversion image format options
$pabi_lang['Format Options'] = 'Format Options';

// Label above format options
$pabi_lang['Save as...'] = 'Save as...';

// label for original format option
$pabi_lang['Original format'] = 'Original format';

// label for jpeg quality
$pabi_lang['JPEG Quality'] = 'JPEG Quality';

// JPEG quality option labels
$pabi_lang['50'] = 'Small Filesize';
$pabi_lang['60'] = 'Medium Filesize';
$pabi_lang['75'] = 'Good Quality';
$pabi_lang['85'] = 'High Quality';
$pabi_lang['100'] = 'Best Quality';

// instructions for converting images to a different format.
// This should be HTML code as it is not escaped with htmlspecialchars
$pabi_lang['Convert Instructions'] = <<<EOL
Choose the format to convert your images to. Supported formats
are jpeg, png and gif.
<br /><br />
You can optionally keep all images in their original format.
<br /><br />
If converting images to jpeg you can specify the quality level.
Higher quality = Larger filesize.
EOL;

// Heading above convert images submit button
$pabi_lang['Convert Again'] = 'Convert Again';

// Heading above upload submit button
$pabi_lang['Upload & Convert'] = 'Upload & Convert';

// Message displayed whilst uploading and converting images
$pabi_lang['Working... Please Wait :)'] = 'Working... Please Wait :)';

// Label on Convert Submit Button
$pabi_lang['Convert Images'] = 'Convert Images';


/************** ERROR MESSAGES (in functions.php) ********************************/

// uploaded filesize too large
$pabi_lang['Your uploaded file is too large'] = 'Your uploaded file is too large';

// file upload error - incomplete file uploaded
$pabi_lang['The upload was interrupted. Please try again later'] = 'The upload was interrupted. Please try again later';

// user has attempted to convert without uploading any images
$pabi_lang['You did not upload any images'] = 'You did not upload any images';

// server configuration error with file upload
$pabi_lang['A server error occurred. Please try again later'] = 'A server error occurred. Please try again later';

// unsupported / unrecognised file format
$pabi_lang['Unknown File Format'] = 'Unknown File Format';

// file is too large
$pabi_lang['file too large.'] = 'file too large.';

// error reading zip archive
$pabi_lang['Unable to read from zip archive'] = 'Unable to read from zip archive';



